### ISSUE TITLE
Donation rate per week in https://royaleapi.com/clan/#tag

### ISSUE THREAD

**Issue by Tithanium** [RoyaleAPI/cr-api-ux#79]
Currently, the max of donation is provided. Would it be also possible to add 
1) a column with the donation rate (the average slope of the data in clan history) ? (Is the player usually giving a lot ?)
2) a column with the average of battle (all type included) per day or week ? (Is the player playing a lot ?)
3) a column where we have the ratio between given and received cards ? (Is the player parasiting the community ?)
This would be cool to assess the recent activity of each clan member...

**Comment by 6Sean** [comment]
This is a very old open issue.  Cards given & received has been added in.  For clans with history tracked, you can see similar data to what you've requested.  It's unlikely that all clans will be tracked like this since the calls are very expensive.

You can see examples here:
https://royaleapi.com/clan/28VVQPV9/history?field=donations
https://royaleapi.com/clan/28VVQPV9/history/v2?field=donations
https://royaleapi.com/clan/28VVQPV9/history?field=trophies

> Clan history is an excellent way to for clans to track activity over time. However, it is not enabled by default. In order to enable it, add the URL RoyaleAPI.com or cr-api.com in your clan description and we will start tracking it.

@Tithanium I'll close this, but please reference the above and let me know if you have any questions.
